#!/bin/bash

#Bbash script to move pertinent files from jobs and pull file names
#param h - put jobs containing this string into list
#param i - ignore jobs that contain this string

SETRUN_ARGS="$@"
hinge="DefaultHinge"
ignore_string="DefaultIgnore"
iter=0
iterspace=1
#subdir=~/crystals/NMA/phasediagram/datasets/May_5_LJ/


#options passed in from the users
while getopts "h:i:" opt; do
        case $opt in
        h )
                hinge=$OPTARG
                ;;
        i )
                ignore_string=$OPTARG
                ;;
	esac
done

mkdir outfiles
subdir=outfiles/

#Move all jobs
if [ "$hinge" == "DefaultHinge" ] && [ $ignore_string == "DefaultIgnore" ]; then
	for direct in $(ls -l | egrep '^d' | awk '{print $9}'); do
			
		a="polymorph"
		if [ "$(echo $direct | grep "FCC")" == $direct ]; then
			b="FCC"		

		elif [ "$(echo $direct | grep "HCP")" == $direct ]; then
			b="HCP"
	
		else 
			b="BCC"
		fi
		c="pressure"
		d=$( less $direct/log.lammps | grep "fix" | awk '{print $6}' )
		te=$( less $direct/log.lammps | grep "fix" | awk '{print $10}' )
		tf="temp"

		newname="$a$b$c$d$tf$te.xvg"
	
		cp $direct/log.lammps $subdir/$newname

		echo $newname

		if [ $b == "HCP" ]; then
			echo -e "$d \t $te" >> "${subdir}/prestemp.txt"
		fi

	let "iter=$iter+1"	
	done

elif [ $ignore_string == "DefaultIgnore" ]; then
	for direct in $(ls -l | egrep '^d' | awk '{print $9}' | grep "$(echo $hinge | awk '{print $1}')" | grep "$(echo $hinge | awk '{print $2}')" | grep "$(echo $hinge | awk '{print $3}')"); do
			
		a="polymorph"
		if [ "$(echo $direct | grep "FCC")" == $direct ]; then
			b="FCC"		

		elif [ "$(echo $direct | grep "HCP")" == $direct ]; then
			b="HCP"
	
		else 
			b="BCC"
		fi
		c="pressure"
		d=$( less $direct/log.lammps | grep "fix" | awk '{print $6}' )
		te=$( less $direct/log.lammps | grep "fix" | awk '{print $10}' )
		tf="temp"

		newname="$a$b$c$d$tf$te.xvg"
	
		cp $direct/log.lammps $subdir/$newname

		echo $newname

		if [ $b == "HCP" ]; then
			echo -e "$d \t $te" >> "${subdir}/prestemp.txt"
		fi

	let "iter=$iter+1"	
	done

elif [ "$hinge" == "DefaultHinge" ]; then
	for direct in $(ls -l | egrep '^d' | awk '{print $9}' | grep -v $ignore_string); do
			
		a="polymorph"
		if [ "$(echo $direct | grep "FCC")" == $direct ]; then
			b="FCC"		

		elif [ "$(echo $direct | grep "HCP")" == $direct ]; then
			b="HCP"
	
		else 
			b="BCC"
		fi
		c="pressure"
		d=$( less $direct/log.lammps | grep "fix" | awk '{print $6}' )
		te=$( less $direct/log.lammps | grep "fix" | awk '{print $10}' )
		tf="temp"

		newname="$a$b$c$d$tf$te.xvg"
	
		cp $direct/log.lammps $subdir/$newname

		echo $newname

		if [ $b == "HCP" ]; then
			echo -e "$d \t $te" >> "${subdir}/prestemp.txt"
		fi

	let "iter=$iter+1"	
	done

else
	for direct in $(ls -l | egrep '^d' | awk '{print $9}' | grep "$(echo $hinge | awk '{print $1}')" | grep "$(echo $hinge | awk '{print $2}')" | grep "$(echo $hinge | awk '{print $3}')" | grep -v $ignore_string); do			
		a="polymorph"
		if [ "$(echo $direct | grep "FCC")" == $direct ]; then
			b="FCC"		

		elif [ "$(echo $direct | grep "HCP")" == $direct ]; then
			b="HCP"
	
		else 
			b="BCC"
		fi
		c="pressure"
		d=$( less $direct/log.lammps | grep "fix" | awk '{print $6}' )
		te=$( less $direct/log.lammps | grep "fix" | awk '{print $10}' )
		tf="temp"

		newname="$a$b$c$d$tf$te.xvg"
	
		cp $direct/log.lammps $subdir/$newname

		echo $newname

		if [ $b == "HCP" ]; then
			echo -e "$d \t $te" >> "${subdir}/prestemp.txt"
		fi

	let "iter=$iter+1"	
	done
fi







