#!/bin/bash
#BASH SCRIPT TO CONVERT THE JOB EDR FILE INTO XVG
#param f - The name of the input edr file
#param o - The name of the output.xvg file
#param n - The number to pipe in to g_energy

# Exporting gromacs commands
export GRO_energy="gmx energy"

SETRUN_ARGS="$@"
inputfile="PROD.edr"
inputfile2="EQ.edr"
outputfile="energy.xvg"
num=13

#options passed in from the users
while getopts "f:o:n:" opt; do
        case $opt in
        f )
                inputfile=$OPTARG
                ;;
        o )
                outputfile=$OPTARG
                ;;
	n )
		num=$OPTARG
		;;		
        esac
done

#Extract all relevant thermodynamic information using g_energy
echo Total-Energy | ${GRO_energy} -f $inputfile2 -o "equil_energy.xvg"
echo Potential | ${GRO_energy} -f $inputfile2 -o "equil_potenergy.xvg"

echo Pressure | ${GRO_energy} -f $inputfile2 -o "equil_pressure.xvg"
echo Volume | ${GRO_energy} -f $inputfile2 -o "equil_volume.xvg"
echo Total-Energy | ${GRO_energy} -f $inputfile -o "energy.xvg" | grep Energy > avgenergy.xvg
echo Potential | ${GRO_energy} -f $inputfile -o "potenergy.xvg" | grep Potential > avgpotenergy.xvg
echo Pressure | ${GRO_energy} -f $inputfile -o "pressure.xvg" | grep Pressure > avgpressure.xvg
echo Volume | ${GRO_energy} -f $inputfile -o "volume.xvg" | grep Volume > avgvolume.xvg
echo -e "Potential\nKinetic\nTotal\nTemperature\nVolume\nPressure" | ${GRO_energy} -f $inputfile -o fullenergy.xvg

#Also, create a gro file which has all of the configurations in it.
#echo "0 0" | trjconv_d -s benzene_restraint.gro -f benzene_PROD.trr -o benzene_Traj.gro -pbc nojump -ndec 8
