# Input file for setting up a PSCP between two crystalline polymorphs along with intermediate temperature samples

# General input parameters
gen_in:
    anneal_temp: 400
    cores: 7
    cutoff: 8
    hinge: DefaultHinge
    independent: same
    integrator: sd
    molecule: none
    number_of_molecules: none
    output_directory: output
    polymorph_num: none
    potential: oplsaa
    pressure: 1
    submission_script: submit_cluster.slurm
    template_path: none
    thermostat: nose-hoover

PSCP_in:
    PSCP_temperature: 200
    run_PSCP: [False,False,False,False]
    equil_steps: [0,0,0,0]
    exponent: [-2.,-2.,4.,1.]
    itp_file: []
    k: [0,1000,1000,1000000,1000000]
    prod_setps: [10000000,10000000,10000000,10000000]
    run_bonded_interactions: True
    spacing: [5,5,1,2]

QHA_in:
    boltz_QHA: False
    Tinker_template: re_setup/molecule.xyz
    boltz_temperatures: none
    max_frames: 10
    runfiles: []

PSCP_out:
    dG: []
    ddG: []

temp_in:
    # Input parameters for setup_Temperature
    run_temperature: False
    simulation_package: gromacs
    temperatures_unsampled: 
    temperatures: 50 100 200 300
    charge: 0.1150
    temp_anneal_steps: 500
    temp_equil_steps: 1000000
    temp_prod_steps: 10000000
    barostat: Parrinello-Rahman
    k_max: 1000
    ensemble: NPT
    prodoutputs: 1000

rep_exch_in:
    # Settings for replica exchange
    T_min: 10
    T_max: 400
    prob_overlap: 0.3
    cores_per_replica: 1
    cores_per_node: 28
