#!/bin/bash


#BASH SCRIPT TO AUTOMATICALLY SET UP BENZENE MD SIMULATIONS OVER A T AND P RANGE
#By: Natalie Schieber 5/13/15
#param n - polymorph number (all 3 will be used if none is given)
#param C - Minimum temperature in K
#param H - Maximum temperature in K
#param S - Temperature spacing in K
#param P - Minimum pressure in bar
#param Y - Maximum pressure in bar
#param s - Pressure spacing in bar
#param N - Number of benzene molecules
#param I - Number of independent benzene molecules (the remainder will be averaged)
#param e - Number of steps in the equilibration step
#param p - Number of steps in the production step
#param i - Integrator
#param t - Thermostat
#param b - Barostat
#param r - vdw/coulomb cutoff distance (in angstroms)
#param u - potential to be used in the simulation
#param h - optional string hinge to add to the job

#=============================================================================================
# SETUP DEFAULT VALUES AND READ IN PARAMETERS FROM USER
#=============================================================================================


SETRUN_ARGS="$@"
polymorph_num="p1 p2 p3"
TMIN=200
TMAX=200
TSPACE=10
PMIN=11
PMAX=55000
PSPACE=700
MOLECULE="benzene"
MOLECULES=72
INDEPENDENT=72
equil_steps=1000000
prod_steps=8000000
integrator="sd"
thermostat="nose-hoover"
barostat="Parrinello-Rahman"
CHARGE="0.0"
POTENTIAL="oplsaa"
ensemble="NPT"
hinge="DefaultHinge"
PRODOUTPUTS="20000"
PRODTRROUTPUTS="300"
RAD=7



#options passed in from the users
while getopts "n:C:H:S:P:Y:s:N:I:e:p:i:t:b:u:h:E:o:c:" opt; do
        case $opt in
        n )
                polymorph_num=$OPTARG
                ;;
	C )
		TMIN=$OPTARG
		;;
	H )
		TMAX=$OPTARG
		;;
	S )
		TSPACE=$OPTARG
		;;
        P )
                PMIN=$OPTARG
                ;;
	Y )
		PMAX=$OPTARG
		;;
	s )
		PSPACE=$OPTARG
		;;
        N )
                MOLECULES=$OPTARG
                ;;
	I )
                INDEPENDENT=$OPTARG
                ;;
        e )
                equil_steps=$OPTARG
                ;;
        p )
                prod_steps=$OPTARG
                ;;
        i )
                integrator=$OPTARG
                ;;
        t )
                thermostat=$OPTARG
                ;;
        b )
                barostat=$OPTARG
                ;;
	u )
                POTENTIAL=$OPTARG
                ;;
        h )
                hinge=$OPTARG
                ;;
	E )
		ensemble=$OPTARG
		;;
        o )
                PRODOUTPUTS=$OPTARG
		PRODTRROUTPUTS=$OPTARG
                ;;
	c )
		CHARGE=$OPTARG
		;;

        esac
done





#==============================================================================================
# ENSURE THAT INPUTS HAVE BEEN PROPERLY ENTERED
#=============================================================================================

#TEMPERATURE
if [ $TMIN == -1 ]; then
	echo "Invalid Minimum Temperature: $TMIN"
	exit 1
fi

#PRESSURE
if [ $PMIN == -1 ]; then
	echo "Invalid Minimum Pressure: $PMIN"
	exit 1
fi


#TEMPERATURE SPACING
if [ "$TSPACE" -le "0" ]; then
	echo "Invalid Temperature Spacing: $PSPACE"
	exit 1
fi

#PRESSURE SPACING
if [ "$PSPACE" -le "0" ]; then
	echo "Invalid Pressure Spacing: $PSPACE"
	exit 1
fi

#NUMBER OF MOLECULES (currently only 72, 108, 256 is accepted)
if [ $MOLECULES != 256 ] && [ $MOLECULES != 108 ] && [ $MOLECULES != 72 ]; then
        echo "Unsupported number of molecules: $MOLECULES"
        exit 1
fi

#NUMBER OF INDEPENDENT MOLECULES (currently only 4, 8, 16, 32, 72, 108, 256 is accepted)
if [ $INDEPENDENT != 12 ] && [ $INDEPENDENT != 108 ] && [ $INDEPENDENT != 72 ] && [ $INDEPENDENT != 32 ] && [ $INDEPENDENT != 16 ] && [ $INDEPENDENT != 8 ] && [ $INDEPENDENT != 4 ] && [ $INDEPENDENT != 2 ]; then
        echo "Unsupported number of independent molecules: $INDEPENDENT"
        exit 1
elif [ "$MOLECULES" -lt "$INDEPENDENT" ]; then
        echo "Number of total molecules is less than the number of independent molecules!"
        echo "Total Molecules: $MOLECULES"
        echo "Independent Molecules: $INDEPENDENT"
        exit 1
fi

#INTEGRATOR
if [ $integrator != "md" ] && [ $integrator != "md-vv" ] && [ $integrator != "sd" ]; then
        echo "Unrecognized integrator: $integrator"
        exit 1
fi


#POTENTIAL
if [ "$POTENTIAL" != "oplsaa" ] && [ "$POTENTIAL" != "oplsaafakeg" ] && [ "$POTENTIAL" != "oplsaafakea" ] && [ "$POTENTIAL" != "amoeba09" ] && [ "$POTENTIAL" != "gromos" ]; then
        echo "Invalid Potential: $POTENTIAL"
        echo "Supported Potentials: oplsaa oplsaafakeg oplsaafakea amoeba09 gromos"
        exit 1
fi


#=============================================================================================
# SETUP Temp Pressure Grid
#=============================================================================================

pressure=$PMIN

while [ "$pressure" -lt "$PMAX" ]; do
	temp=$TMIN
	
	while [ "$temp" -lt "$TMAX" ]; do
		for poly in $polymorph_num; do
			setup_molecule -M $MOLECULE -n $poly -T $temp -P $pressure -N $MOLECULES -I $INDEPENDENT -e $equil_steps -p $prod_steps -u $POTENTIAL -h $hinge -E $ensemble -i $integrator -t $thermostat -b $barostat -c $CHARGE -o $PRODOUTPUTS -r $RAD
		done
	let "temp=$temp+$TSPACE"

	done

	for poly in $polymorph_num; do
		setup_molecule -M $MOLECULE -n $poly -T $TMAX -P $pressure -N $MOLECULES -I $INDEPENDENT -e $equil_steps -p $prod_steps -u $POTENTIAL -h $hinge -E $ensemble -i $integrator -t $thermostat -b $barostat -c $CHARGE -o $PRODOUTPUTS -r $RAD
	done
let "pressure=$pressure+$PSPACE"
done

#final pressure off by one exception
temp=$TMIN
while [ "$temp" -lt "$TMAX" ]; do
	for poly in $polymorph_num; do
		setup_molecule -M $MOLECULE -n $poly -T $temp -P $PMAX -N $MOLECULES -I $INDEPENDENT -e $equil_steps -p $prod_steps -u $POTENTIAL -h $hinge -E $ensemble -i $integrator -t $thermostat -b $barostat -c $CHARGE -o $PRODOUTPUTS -r $RAD
        done
        let "temp=$temp+$TSPACE"
done

for poly in $polymorph_num; do
	setup_molecule -M $MOLECULE -n $poly -T $TMAX -P $PMAX -N $MOLECULES -I $INDEPENDENT -e $equil_steps -p $prod_steps -u $POTENTIAL -h $hinge -E $ensemble -i $integrator -t $thermostat -b $barostat -c $CHARGE -o $PRODOUTPUTS -r $RAD
done
