#!/bin/bash

# BASH SCRIPT TO ADD FULL PRECISION TO A GRO FILE GIVEN A TINKER XYZ FILE
# param g - The name of the .gro file
# param x - The name of the .xyz file

SETRUN_ARGS="$@"
grofile="frame.gro"
xyzfile="frame.xyz"

#=============================================================================================
# READ IN USER INPUTS
#=============================================================================================
while getopts "g:x:" opt; do
        case $opt in
        g )
                grofile=$OPTARG
                ;;
        x )
                xyzfile=$OPTARG
                ;;
        esac
done

#=============================================================================================
# DETERMINE THE NUMBER OF ATOMS IN THE FILE
#=============================================================================================
numatoms=$(sed '2q;d' $grofile)
echo "Numatoms: $numatoms"

#=============================================================================================
# FIND THE LINES AND REPLACE THE NUMBERS WITH HIGHER PRECISION
#=============================================================================================

#Store the first two lines of the gro file
firstline=$(head -1 $grofile)
secondline=$(head -2 $grofile | tail -1)
lastline=$(tail -1 $grofile)

#Paste the atom names in a temporary file
tail -n +3 $grofile | head -n -1 | awk '{print $1, $2, $3}' > tempatoms.txt


#Paste the new xyz coordinates in a temporary file
if [ $(head -2 $xyzfile | tail -1 | awk '{print $1}') == "1" ] && [ $(head -2 $xyzfile | tail -1 | awk '{print $2}') == "C" ]; then
    tail -n +2 $xyzfile | awk '{print $3, $4, $5}' > tempcoords.txt
else
    tail -n +3 $xyzfile | awk '{print $3, $4, $5}' > tempcoords.txt
fi

#Combine the three files together into a new xyz file
paste tempatoms.txt tempcoords.txt > $grofile

#Now add the first two lines to the top of the file
sed -i "1s/^/${secondline}\n/" $grofile
sed -i "1s/^/${firstline}\n/" $grofile
sed -i "\$a${lastline}" $grofile

