#!/bin/bash

#Bbash script to move pertinent files from jobs and pull file names
#param h - put jobs containing this string into list
#param i - ignore jobs that contain this string

SETRUN_ARGS="$@"
hinge="DefaultHinge"
ignore_string="DefaultIgnore"
en="potenergy"
vol="volume"
iter=0
iterspace=1
subdir=~/crystals/NMA/benzenephase/dec14


#options passed in from the users
while getopts "h:i:" opt; do
        case $opt in
        h )
                hinge=$OPTARG
                ;;
        i )
                ignore_string=$OPTARG
                ;;
	esac
done




#Move all jobs
if [ "$hinge" == "DefaultHinge" ] && [ $ignore_string == "DefaultIgnore" ]; then
	for direct in $(ls -l | egrep '^d' | awk '{print $9}'); do
			
		a="polymorph"
		if [ "$(echo $direct | grep "p1")" == $direct ]; then
			b="p1"
		

		elif [ "$(echo $direct | grep "p2")" == $direct ]; then
			b="p2"
		

		else 
			b="p3"
		fi
		c="pressure"
		d=$( less $direct/benzene_production.mdp | grep "ref_p" | awk '{print $3}' )
		te=$( less $direct/benzene_production.mdp | grep "gen_temp" | awk '{print $3}' )
		tf="temp"
		x="vol"
		y="en"
		am="amoeba"
		newnameen="$a$b$c$d$tf$te$y.xvg"
		newnamevol="$a$b$c$d$tf$te$x.xvg"
		newnameamo="$a$b$c$d$tf$te$y$am.xvg"

		
		cp $direct/potenergy.xvg $subdir/$newnameen
		cp $direct/amoeba09_energy.xvg $subdir/$newnameamo
		
		
		echo $newnameen
		echo $newnamevol	

			
		cp $direct/volume.xvg $subdir/$newnamevol
		if [ $b == "p1" ]; then
			echo -e "$d \t $te" >> "${subdir}/prestemp.txt"
		fi

	let "iter=$iter+1"	
	done

elif [ $ignore_string == "DefaultIgnore" ]; then
	for direct in $(ls -l | egrep '^d' | awk '{print $9}' | grep "$(echo $hinge | awk '{print $1}')" | grep "$(echo $hinge | awk '{print $2}')" | grep "$(echo $hinge | awk '{print $3}')"); do
		a="polymorph"
		if [ "$(echo $direct | grep "p1")" == $direct ]; then
			b="p1"
		

		elif [ "$(echo $direct | grep "p2")" == $direct ]; then
			b="p2"
		

		else 
			b="p3"
		fi
		c="pressure"
		d=$( less $direct/benzene_production.mdp | grep "ref_p" | awk '{print $3}' )
		te=$( less $direct/benzene_production.mdp | grep "gen_temp" | awk '{print $3}' )
		tf="temp"
		x="vol"
		y="en"
		newnameen="$a$b$c$d$tf$te$y.xvg"
		newnamevol="$a$b$c$d$tf$te$x.xvg"
		
		cp $direct/potenergy.xvg $subdir/$newnameen
			

			
		cp $direct/volume.xvg $subdir/$newnamevol
		if [ $b == "p1" ]; then
			echo -e "$d \t $te" >> "${subdir}/prestemp.txt"
		fi
	
	done

elif [ "$hinge" == "DefaultHinge" ]; then
	for direct in $(ls -l | egrep '^d' | awk '{print $9}' | grep -v $ignore_string); do
		a="polymorph"
		if [ "$(echo $direct | grep "p1")" == $direct ]; then
			b="p1"
		

		elif [ "$(echo $direct | grep "p2")" == $direct ]; then
			b="p2"
		

		else 
			b="p3"
		fi
		c="pressure"
		d=$( less $direct/benzene_production.mdp | grep "ref_p" | awk '{print $3}' )
		te=$( less $direct/benzene_production.mdp | grep "gen_temp" | awk '{print $3}' )
		tf="temp"
		x="vol"
		y="en"
		newnameen="$a$b$c$d$tf$te$y.xvg"
		newnamevol="$a$b$c$d$tf$te$x.xvg"


		cp $direct/potenergy.xvg $subdir/$newnameen
			

			
		cp $direct/volume.xvg $subdir/$newnamevol
		if [ $b == "p1" ]; then
			echo -e "$d \t $te" >> "${subdir}/prestemp.txt"
		fi
			
	
	done

else
	for direct in $(ls -l | egrep '^d' | awk '{print $9}' | grep "$(echo $hinge | awk '{print $1}')" | grep "$(echo $hinge | awk '{print $2}')" | grep "$(echo $hinge | awk '{print $3}')" | grep -v $ignore_string); do
		a="polymorph"
		if [ "$(echo $direct | grep "p1")" == $direct ]; then
			b="p1"
		

		elif [ "$(echo $direct | grep "p2")" == $direct ]; then
			b="p2"
		

		else 
			b="p3"
		fi
		c="pressure"
		d=$( less $direct/benzene_production.mdp | grep "ref_p" | awk '{print $3}' )
		x="vol"
		y="en"
		te=$( less $direct/benzene_production.mdp | grep "gen_temp" | awk '{print $3}' )
		tf="temp"
		newnameen="$a$b$c$d$tf$te$y.xvg"
		newnamevol="$a$b$c$d$tf$te$x.xvg"

		
		cp $direct/potenergy.xvg $subdir/$newnameen
			

			
		cp $direct/volume.xvg $subdir/$newnamevol
		if [ $b == "p1" ]; then
			echo -e "$d \t $te" >> "${subdir}/prestemp.txt"
		fi
	
	done


fi







