#!/bin/bash

SETRUN_ARGS="$@"
basedirpython=/home/nasc5274/crystals/FENEX
basedirdata=/home/nasc5274/NMA/phasediagram/datasets
jobdir=/home/nasc5274/crystals/NMA/jobs
runname=FENEXoplsrun
tempfile="${basedirpython}/temp.txt"
presfile="${basedirpython}/pres.txt"
tmin=50

temp=$(sed -n "$linenum"p $tempfile)
temp=$( printf "%.0f" $temp )
temp=$(sed -n "$linenum"p $presfile)
temp=$( printf "%.0f" $pres )


while [ "$temp" -lt "$tmin" ]; do


	cd jobdir
	setup_FENEXLJ -P 
	cd "LJ_FCC_8_${temp}K_${pres}"
	lmp_serial -in in.LJ

	createlist


	cd $basedirpython
	python FENEXiter.py -h "${runname}_${temp}"
	temp=$(sed -n "$linenum"p $tempfile)
	temp=$( printf "%.0f" $temp )
	pres=$(sed -n "$linenum"p $presfile)
	pres=$( printf "%.0f" $pres )

done


