#!/bin/bash


#BASH SCRIPT TO AUTOMATICALLY SET UP BENZENE MD SIMULATIONS OVER A T AND P RANGE
#By: Natalie Schieber 5/13/15
#param n - polymorph number (all 3 will be used if none is given)
#param C - Minimum temperature in K
#param H - Maximum temperature in K
#param S - Temperature spacing in K
#param P - Minimum pressure in bar
#param Y - Maximum pressure in bar
#param s - Pressure spacing in bar
#param N - Number of benzene molecules
#param I - Number of independent benzene molecules (the remainder will be averaged)
#param e - Number of steps in the equilibration step
#param p - Number of steps in the production step
#param i - Integrator
#param t - Thermostat
#param b - Barostat
#param r - vdw/coulomb cutoff distance (in angstroms)
#param u - potential to be used in the simulation
#param h - optional string hinge to add to the job

#=============================================================================================
# SETUP DEFAULT VALUES AND READ IN PARAMETERS FROM USER
#=============================================================================================

SETRUN_ARGS="$@"
polymorph_num="fcc bcc hcp"
TMIN=10
TMAX=110
TSPACE=20
PMIN=1
PMAX=4000
PSPACE=400
equil_steps=1000000
prod_steps=8000000
integrator="md"
thermostat="v-rescale"
barostat="Parrinello-Rahman"
hinge="DefaultHinge"
ensemble="NPT"

#options passed in from the users
while getopts "n:C:H:S:P:Y:s:e:p:i:t:b:h:E:" opt; do
        case $opt in
        n )
                polymorph_num=$OPTARG
                ;;
	C )
		TMIN=$OPTARG
		;;
	H )
		TMAX=$OPTARG
		;;
	S )
		TSPACE=$OPTARG
		;;
        P )
                PMIN=$OPTARG
                ;;
	Y )
		PMAX=$OPTARG
		;;
	s )
		PSPACE=$OPTARG
		;;
        e )
                equil_steps=$OPTARG
                ;;
        p )
                prod_steps=$OPTARG
                ;;
        i )
                integrator=$OPTARG
                ;;
        t )
                thermostat=$OPTARG
                ;;
        b )
                barostat=$OPTARG
                ;;
        h )
                hinge=$OPTARG
                ;;
	E )
		ensemble=$OPTARG
		;;
        esac
done





#==============================================================================================
# ENSURE THAT INPUTS HAVE BEEN PROPERLY ENTERED
#=============================================================================================

#TEMPERATURE
if [ $TMIN == -1 ]; then
	echo "Invalid Minimum Temperature: $TMIN"
	exit 1
fi

#PRESSURE
if [ $PMIN == -1 ]; then
	echo "Invalid Minimum Pressure: $PMIN"
	exit 1
fi

#POLYMORPH NUMBER
#if [ $polymorph_num != "fcc" ] && [ $polymorph_num != "bcc" ] && [ $polymorph_num != "hcp" ] && [ $polymorph_num != "fcc bcc" ] && [ $polymorph_num != "fcc hcp" ] && [ $polymorph_num != "bcc hcp" ] && [ $polymorph_num != "fcc bcc hcp" ]; then
#        echo "Unrecognized polymorph Number: $polymorph_num"
#        exit 1
#fi

#TEMPERATURE SPACING
if [ "$TSPACE" -le "0" ]; then
	echo "Invalid Temperature Spacing: $PSPACE"
	exit 1
fi

#PRESSURE SPACING
if [ "$PSPACE" -le "0" ]; then
	echo "Invalid Pressure Spacing: $PSPACE"
	exit 1
fi

#INTEGRATOR
if [ $integrator != "md" ] && [ $integrator != "md-vv" ]; then
        echo "Unrecognized integrator: $integrator"
        exit 1
fi


#=============================================================================================
# SETUP Temp Pressure Grid
#=============================================================================================

pressure=$PMIN

while [ "$pressure" -lt "$PMAX" ]; do
	temp=$TMIN
	
	while [ "$temp" -lt "$TMAX" ]; do
		for poly in $polymorph_num; do
			setup_LJ -n $poly -T $temp -P $pressure -e $equil_steps -p $prod_steps -h $hinge -E $ensemble -i $integrator -t $thermostat -b $barostat
		done
	let "temp=$temp+$TSPACE"

	done

	for poly in $polymorph_num; do
		setup_LJ -n $poly -T $TMAX -P $pressure -e $equil_steps -p $prod_steps -h $hinge -E $ensemble -i $integrator -t $thermostat -b $barostat
	done
let "pressure=$pressure+$PSPACE"
done

#final pressure off by one exception
temp=$TMIN
while [ "$temp" -lt "$TMAX" ]; do
	for poly in $polymorph_num; do
       	setup_LJ -n $poly -T $temp -P $PMAX -e $equil_steps -p $prod_steps -h $hinge -E $ensemble -i $integrator -t $thermostat -b $barostat
        done
        let "temp=$temp+$TSPACE"
done

for poly in $polymorph_num; do
        setup_LJ -n $poly -T $TMAX -P $PMAX -e $equil_steps -p $prod_steps -h $hinge -E $ensemble -i $integrator -t $thermostat -b $barostat
done
