#!/bin/bash

SETRUN_ARGS="$@"
p1dir="Polymorph1"
p2dir="Polymorph2"


export GRO_LOC="/home/nps5kd/gromacs_forceavg/install/bin"

export SCRIPT_LOC="/home/nps5kd/crystals"
hinge="_p2_"
ignore_string="_p1_"
while getopts "p1:p2:" opt; do
        case $opt in
        p1 )
                p1dir=$OPTARG
                ;;
	p2 )
                p2dir=$OPTARG
                ;;
	esac
done





for direct in $(ls -l | egrep '^d' | awk '{print $9}' | grep "$(echo $hinge | awk '{print $1}')" | grep "$(echo $hinge | awk '{print $2}')" | grep "$(echo $hinge | awk '{print $3}')" | grep -v $ignore_string); do

	direct2=$( echo ${direct} | sed "s/p2/p1/" )
	
	mappingkabschmany -A $direct -B $direct2

done
