#!/bin/bash

SETRUN_ARGS="$@"
#Default Values
hinge="sdifudsof#usdk78lfjsdf45d"

#options passed in from the users
while getopts "h:" opt; do
        case $opt in
        h )
                hinge=$OPTARG
                ;;
        esac
done

for direct in $(ls -l | awk '{print $9}' | grep $hinge); do
echo "Removing directory: $direct"
rm -rf $direct
done
