#!/bin/bash
#REMOVE ALL FOLDERS WITHIN THE CURRENT DIRECTORY
#BASH SCRIPT TO SUBMIT JOBS ON THE FIR.ITC CLUSTER
#param h - move jobs that contain this string
#param i - ignore jobs that contain this string

SETRUN_ARGS="$@"
hinge="DefaultHinge"
ignore_string="DefaultIgnore"

#options passed in from the users
while getopts "h:i:" opt; do
        case $opt in
        h )
                hinge=$OPTARG
                ;;
        i )
                ignore_string=$OPTARG
                ;;
        esac
done

#Delete jobs that contain the hinge but not the ignore string

#Delete all jobs
if [ "$hinge" == "DefaultHinge" ] && [ $ignore_string == "DefaultIgnore" ]; then
        for direct in $(ls -l | egrep '^d' | awk '{print $9}'); do
                echo "Deleting job: $direct"
                rm -rf $direct
        done
#Delete all jobs containing the hinge
elif [ $ignore_string == "DefaultIgnore" ]; then
        for direct in $(ls -l | egrep '^d' | awk '{print $9}' | grep "$(echo $hinge | awk '{print $1}')" | grep "$(echo $hinge | awk '{print $2}')" | grep "$(echo $hinge | awk '{print $3}')"); do
                echo "Deleting job: $direct"
                rm -rf $direct
        done
#Delete all jobs except those containing the ignore string
elif [ "$hinge" == "DefaultHinge" ]; then
        for direct in $(ls -l | egrep '^d' | awk '{print $9}' | grep -v $ignore_string); do
                echo "Deleting job: $direct"
                rm -rf $direct
        done
else
        for direct in $(ls -l | egrep '^d' | awk '{print $9}' | grep "$(echo $hinge | awk '{print $1}')" | grep "$(echo $hinge | awk '{print $2}')" | grep "$(echo $hinge | awk '{print $3}')" | grep -v $ignore_string); do
                echo "Deleting job: $direct"
                rm -rf $direct
        done
fi
