#!/bin/bash

#BASH SCRIPT TO AUTOMATICALLY SET UP BENZENE MD SIMULATIONS FOR INITIAL NPT EQUILIBRATION
#By: Eric Dybeck 03/31/2014
#param n - polymorph number (all 3 will be used if none is given)
#param M - Molecule name
#param T - Temperature in K
#param P - Pressure in bar
#param N - Number of benzene molecules
#param I - Number of independent benzene molecules (the remainder will be averaged)
#param e - Number of steps in the equilibration step
#param p - Number of steps in the production step
#param i - Integrator
#param t - Thermostat
#param b - Barostat
#param a - number of cores (threads) to run on
#param r - vdw/coulomb cutoff distance (in angstroms)
#param u - potential to be used in the simulation
#param h - optional string hinge to add to the job
#param E - specify the Thermodynamic Ensemble that will be used
#param o - number of production outputs

#=============================================================================================
# SETUP DEFAULT VALUES AND READ IN PARAMETERS FROM USER
#=============================================================================================

SETRUN_ARGS="$@"
polymorph_num="p1 p2 p3"
TEMP=200
PRESSURE=1
MOLECULE="benzene"
MOLECULES=72
INDEPENDENT="same"
equil_steps=1000000
prod_steps=10000000
PRODOUTPUTS=100
integrator="sd"
thermostat="nose-hoover"
barostat="berendsen"
cores=1
CUTOFF="8"
POTENTIAL="oplsaa"
hinge="DefaultHinge"
ENSEMBLE="NPT"

#options passed in from the users
while getopts "n:M:T:P:N:I:e:p:i:t:b:a:r:u:h:E:o:" opt; do
        case $opt in
        n )
                polymorph_num=$OPTARG
                ;;
	M )
                MOLECULE=$OPTARG
                ;;	
	T )
		TEMP=$OPTARG
		;;
        P )
                PRESSURE=$OPTARG
                ;;
        N )
                MOLECULES=$OPTARG
                ;;
	I )
                INDEPENDENT=$OPTARG
                ;;
        e )
                equil_steps=$OPTARG
                ;;
        p )
                prod_steps=$OPTARG
                ;;
        i )
                integrator=$OPTARG
                ;;
        t )
                thermostat=$OPTARG
                ;;
        b )
                barostat=$OPTARG
                ;;
	a )
                cores=$OPTARG
                ;;
	r )
                CUTOFF=$OPTARG
                ;;
	u )
                POTENTIAL=$OPTARG
                ;;
        E )
                ENSEMBLE=$OPTARG
                ;;
        h )
                hinge=$OPTARG
                ;;
	o )
                PRODOUTPUTS=$OPTARG
		;;
        esac
done

#=============================================================================================
# ENSURE THAT INPUTS HAVE BEEN PROPERLY ENTERED
#=============================================================================================

#TEMPERATURE
if [ $TEMP == -1 ]; then
	echo "Invalid Temperature: $Temp"
	exit 1
fi

#INDEPENDENT MOLECULES
if [ "$INDEPENDENT" == "same" ] || [ "$INDEPENDENT" == "$MOLECULES" ]; then
    INDEPENDENT=$MOLECULES
fi

#INTEGRATOR
if [ $integrator != "md" ] && [ $integrator != "md-vv" ] && [ "$integrator" != "sd" ]; then
        echo "Unrecognized integrator: $integrator"
        exit 1
fi

#SPRING CONSTANT
if [ "$k_max" -lt "0" ]; then
        echo "Invalid spring constant: $k_max"
        exit 1
fi

#CUTOFF RADIUS
if [ "$CUTOFF" -lt "0" ]; then
        echo "Invalid Cutoff Radius: $CUTOFF"
        exit 1
fi

#POTENTIAL
if [ "$POTENTIAL" != "oplsaa" ] && [ "$POTENTIAL" != "oplsaafakeg" ] && [ "$POTENTIAL" != "oplsaafakegb" ] && [ "$POTENTIAL" != "oplsaafakegd" ] && [ "$POTENTIAL" != "designeda" ] && [ "$POTENTIAL" != "gromos" ] && [ "$POTENTIAL" != "drude" ]; then
        echo "Invalid Potential: $POTENTIAL"
        echo "Supported Potentials: oplsaa oplsaafakeg oplsaafakegb oplsaafakegd designeda gromos drude"
        exit 1
fi

#ENSEMBLE
if [ "$ENSEMBLE" != "NVE" ] && [ "$ENSEMBLE" != "NVT" ] && [ "$ENSEMBLE" != "NPT" ]; then
        echo "Invalid Thermodynamic Ensemble: $ENSEMBLE"
        echo "Supported Ensembles: NVE, NVT, NPT"
        exit 1
fi

#HINGE
if [ "$hinge" == "DefaultHinge" ]; then
    hinge="NPT1"
else
    hinge="NPT1_$hinge"
fi

if [ "$POTENTIAL" == "designeda" ] && [ "$ENSEMBLE" == "NPT" ]; then
	echo "WARNING: YOU ARE USING THE DESIGNED POTENTIAL IN NPT"
fi

#=============================================================================================
# SETUP CHARGES
#=============================================================================================

#Loop through each polymorph and create a benzene job
for poly in $polymorph_num; do
	setup_molecule -n $poly -T $TEMP -P $PRESSURE -M $MOLECULE -N $MOLECULES -I $INDEPENDENT -e $equil_steps -p $prod_steps -E $ENSEMBLE -i $integrator -t $thermostat -b $barostat -a $cores -r $CUTOFF -u $POTENTIAL -h $hinge 
done

