#!/bin/bash


#BASH SCRIPT TO AUTOMATICALLY SET UP BENZENE MD SIMULATIONS OVER A T AND P RANGE
#By: Natalie Schieber 5/13/15
#param n - polymorph number (all 3 will be used if none is given)
#param C - Minimum temperature in K
#param H - Maximum temperature in K
#param S - Temperature spacing in K
#param P - Minimum pressure in bar
#param Y - Maximum pressure in bar
#param s - Pressure spacing in barp
#param p - Number of steps in the production step
#param h - optional string hinge to add to the job

#=============================================================================================
# SETUP DEFAULT VALUES AND READ IN PARAMETERS FROM USER
#=============================================================================================

SETRUN_ARGS="$@"
polymorph_num="p1 p2 p3
TMIN=40
TMAX=300
TSPACE=35
PMIN=1
PMAX=10000
PSPACE=760
prod_steps=8000000
hinge="DefaultHinge"
ensemble="NPT"

#options passed in from the users
while getopts "n:C:H:S:P:Y:s:e:p:i:t:b:h:E:" opt; do
        case $opt in
        n )
                polymorph_num=$OPTARG
                ;;
	C )
		TMIN=$OPTARG
		;;
	H )
		TMAX=$OPTARG
		;;
	S )
		TSPACE=$OPTARG
		;;
        P )
                PMIN=$OPTARG
                ;;
	Y )
		PMAX=$OPTARG
		;;
	s )
		PSPACE=$OPTARG
		;;
        p )
                prod_steps=$OPTARG
                ;;
        h )
                hinge=$OPTARG
                ;;
	E )
		ensemble=$OPTARG
		;;
        esac
done





#==============================================================================================
# ENSURE THAT INPUTS HAVE BEEN PROPERLY ENTERED
#=============================================================================================

#TEMPERATURE
if [ $TMIN == -1 ]; then
	echo "Invalid Minimum Temperature: $TMIN"
	exit 1
fi

#PRESSURE
if [ $PMIN == -1 ]; then
	echo "Invalid Minimum Pressure: $PMIN"
	exit 1
fi

#POLYMORPH NUMBER
#if [ $polymorph_num != "p1" ] && [ $polymorph_num != "p2" ] && [ $polymorph_num != "p3" ] && [ $polymorph_num != "p1 p2" ] && [ $polymorph_num != "p1 p3" ] && [ $polymorph_num != "p2 p3" ] && [ $polymorph_num != "p1 p2 p3" ]; then
#        echo "Unrecognized polymorph Number: $polymorph_num"
#        exit 1
#fi


#PRESSURE SPACING
if [ "$PSPACE" -le "0" ]; then
	echo "Invalid Pressure Spacing: $PSPACE"
	exit 1
fi



#=============================================================================================
# SETUP Temp Pressure Grid
#=============================================================================================

pressure=$PMIN

while [ "$pressure" -lt "$PMAX" ]; do
	temp=$TMIN
	
	while [ "$temp" -lt "$TMAX" ]; do
		for poly in $polymorph_num; do
			setup_benzenelammps -n $poly -T $temp -P $pressure -p $prod_steps -h $hinge -E $ensemble -x
		done
	let "temp=$temp+$TSPACE"

	done

	for poly in $polymorph_num; do
		setup_benzenelammps -n $poly -T $temp -P $pressure -p $prod_steps -h $hinge -E $ensemble
	done
let "pressure=$pressure+$PSPACE"
done

#final pressure off by one exception
temp=$TMIN
while [ "$temp" -lt "$TMAX" ]; do
	for poly in $polymorph_num; do
       	setup_benzenelammps -n $poly -T $temp -P $pressure -p $prod_steps -h $hinge -E $ensemble
        done
        let "temp=$temp+$TSPACE"
done

for poly in $polymorph_num; do
        setup_benzenelammps -n $poly -T $temp -P $pressure -p $prod_steps -h $hinge -E $ensemble
done
