#!/bin/bash

SETRUN_ARGS="$@"


export GRO_LOC="/home/nps5kd/gromacs_forceavg/install/bin"

export SCRIPT_LOC="/home/nps5kd/crystals"
echo "here"

for direct in $(ls -l | egrep '^d' | awk '{print $9}'); do
	echo "$direct"
	cd $direct
	rm mappingresults.txt
	python ~/crystals/mappingmbar.py -A potenergyA.xvg -B mappedenergy.xvg
	cd ..
done
