#!/bin/bash

#BASH SCRIPT TO AUTOMATICALLY SET UP A BENZENE MD SIMULATION BASED ON USER SPECIFICATIONS
#By: Eric Dybeck 09/12/2014
#param n - polymorph number in the form 'p1'
#param T - Temperature in K
#param P - Pressure in bar
#param N - Number of benzene molecules
#param I - Number of independent benzene molecules (the remainder will be averaged)
#param e - Number of steps in the equilibration step
#param p - Number of steps in the production step
#param i - Integrator
#param t - Thermostat
#param b - Barostat
#param a - number of cores (threads) to run on
#param k - maximum harmonic restraint constant
#param D - drude oscillator spring constant (%)
#param L - lambda state for the harmonic restraint
#param U - unrestrained lambda value (%)
#param R - restrained lambda value (%)
#param s - spacing between the lambdas
#param f - functional form (exponent) of the spacing between the lambdas
#param G - Gamma state for the interaction dissapearance
#param g - spacing between the gammas
#param d - Percentage for alchemically interpolating the original itp file (%)
#param V - desired box volume (in cubic nm)
#param r - vdw/coulomb cutoff distance (in angstroms)
#param u - potential to be used in the simulation
#param c - charge assigned to the carbon and hydrogen 
#param C - Sigma value for Carbon (% of actual)
#param H - Sigma value for Hydrogen (% of actual) 
#param z - specify which simulation package we will use (gromacs or tinker)
#param h - optional string hinge to add to the job
#param E - specify the Thermodynamic Ensemble that will be used
#param o - number of production outputs

#Give these parameters, the script creates a directory in the jobs folder and copies
#over the relevant .mdp, .gro and topology files to carry out the job. In addition
#the .mdp files are manipulated away from the defaults based on the user specified
#parameters. Finally, local and cluster submission scripts are copied over to allow
#the job to be run.

#=============================================================================================
# SETUP DEFAULT VALUES AND READ IN PARAMETERS FROM USER
#=============================================================================================

SETRUN_ARGS="$@"
#Default Values
polymorph_num="p1"
TEMP=-1
PRESSURE=1
MOLECULES=72
INDEPENDENT=72
equil_steps=100000
prod_steps=40000000
integrator="md"
thermostat="nose-hoover"
barostat="berendsen"
cores=1
k_max=1000
drude_k=100
Lambda=0
MINLAMBDA=0
MAXLAMBDA=0
LSPACING=100
MAXGAMMA=100
MINGAMMA=100
GAMMA=100
GSPACING=100
DELTA=0
EXPONENT=1
VOLUME=-1
CUTOFF="7"
EMOUTPUTS="2000"
EMTRROUTPUTS="2000"
PRODOUTPUTS="4000"
PRODTRROUTPUTS="4000"
PHASE="DefaultPhase"
SIMULATION="gromacs"
POTENTIAL="oplsaa"
ENSEMBLE="NVT"
CHARGE="0.1150"
SigmaC="100"
SigmaH="100"
hinge="DefaultHinge"

export SCRIPT_LOC="/home/nasc5274/crystals/NMA/scripts"

#options passed in from the users
while getopts "n:T:P:N:I:e:p:o:i:t:b:a:k:D:L:U:R:s:f:A:B:G:g:d:V:r:u:c:C:H:z:E:h:" opt; do
        case $opt in
        n )
                polymorph_num=$OPTARG
                ;;
        T )
                TEMP=$OPTARG
                ;;
	P )
		PRESSURE=$OPTARG
		;;
	N )
		MOLECULES=$OPTARG
		;;
	I )
		INDEPENDENT=$OPTARG
		;;
	e )
		equil_steps=$OPTARG
		;;
	p )
		prod_steps=$OPTARG
		;;
	o )
		PRODOUTPUTS=$OPTARG
		PRODTRROUTPUTS=$OPTARG
		;;
	i )
		integrator=$OPTARG
		;;
	t )
		thermostat=$OPTARG
		;;
	b )
		barostat=$OPTARG
		;;
	a )
		cores=$OPTARG
		;;
	k )
		k_max=$OPTARG
		;;
	D )
		drude_k=$OPTARG
		;;
	L )
		Lambda=$OPTARG
		;;
	U )
                MINLAMBDA=$OPTARG
                ;;
        R )
                MAXLAMBDA=$OPTARG
                ;;
        s )
                LSPACING=$OPTARG
                ;;
	f )
		EXPONENT=$OPTARG
		;;
	A )
		MAXGAMMA=$OPTARG
		;;
	B )
		MINGAMMA=$OPTARG
		;;
	G )
		GAMMA=$OPTARG
		;;
	g )
		GSPACING=$OPTARG
		;;
	d )
		DELTA=$OPTARG
		;;
	V )
		VOLUME=$OPTARG
		;;
	r )
		CUTOFF=$OPTARG
		;;
	u )
		POTENTIAL=$OPTARG
		;;
	c )
		CHARGE=$OPTARG
		;;
	C )
		SigmaC=$OPTARG
		;;
	H )
		SigmaH=$OPTARG
		;;
	z )
		SIMULATION=$OPTARG
		;;
	E )
		ENSEMBLE=$OPTARG
		;;
	h )
		hinge=$OPTARG
		;;
        esac
done

#=============================================================================================
# ENSURE THAT INPUTS HAVE BEEN PROPERLY ENTERED
#=============================================================================================

#TEMPERATURE
if [ $TEMP == "-1" ]; then
        echo "Invalid Temperature: $TEMP"
        exit 1
fi

#PRESSURE
if [ "$PRESSURE" -lt "0" ]; then
	echo "Invalid Pressure: $PRESSURE"
	exit 1
fi

#POLYMORPH NUMBER
if [ $polymorph_num != "p1" ] && [ $polymorph_num != "p2" ] && [ $polymorph_num != "p3" ] && [ $polymorph_num != "gas" ]; then
	echo "Unrecognized polymorph Number: $polymorph_num"
	exit 1
elif [ "$polymorph_num" == "gas" ]; then
	integrator="sd"
	PRODOUTPUTS="1000"
        PRODTRROUTPUTS="1000"
	CUTOFF="20"	
fi

#NUMBER OF MOLECULES (currently only 4, 8, 16, 32, 48, 72, 108, 256 is accepted)
if [ $MOLECULES != 256 ] && [ $MOLECULES != 108 ] && [ $MOLECULES != 72 ] && [ $MOLECULES != 48 ] && [ $MOLECULES != 32 ] && [ $MOLECULES != 16 ] && [ $MOLECULES != 8 ]&& [ $MOLECULES != 4 ]; then
	echo "Unsupported number of molecules: $MOLECULES"
	exit 1
fi

#NUMBER OF INDEPENDENT MOLECULES (currently only 4, 8, 16, 32, 72, 108, 256 is accepted)
if [ $INDEPENDENT != 256 ] && [ $INDEPENDENT != 108 ] && [ $INDEPENDENT != 72 ] && [ $INDEPENDENT != 32 ] && [ $INDEPENDENT != 16 ] && [ $INDEPENDENT != 8 ] && [ $INDEPENDENT != 4 ] && [ $INDEPENDENT != 2 ]; then
        echo "Unsupported number of independent molecules: $INDEPENDENT"
        exit 1
elif [ "$MOLECULES" -lt "$INDEPENDENT" ]; then
	echo "Number of total molecules is less than the number of independent molecules!"
	echo "Total Molecules: $MOLECULES"
	echo "Independent Molecules: $INDEPENDENT"
	exit 1
fi

#THERMOSTAT
if [ "$thermostat" != "v-rescale" ] && [ "$thermostat" != "andersen" ] && [ "$thermostat" != "nose-hoover" ]; then
        echo "Unrecognized thermostat: $thermostat"
        echo "Supported thermostats: v-rescale andersen nose-hoover"
        exit 1
fi
#if [ "$GAMMA" == "0" ]; then
#        thermostat="andersen"
#fi
if [ "$barostat" == "parrinello-rahman" ]; then
        thermostat="nose-hoover"
fi

#INTEGRATOR
if [ "$integrator" != "md" ] && [ "$integrator" != "md-vv" ] && [ "$integrator" != "sd" ]; then
	echo "Unrecognized integrator: $integrator"
	exit 1
elif [ "$polymorph_num" = "gas" ]; then
	integrator="sd"
fi
if [ "$thermostat" == "andersen" ]; then
	integrator="md-vv"
fi
#if [ "$barostat" == "parrinello-rahman" ]; then
#	integrator="md"
#elif [ "$barostat" == "MTTK" ]; then
#	integrator="md-vv"
#fi

#BAROSTAT
if [ "$barostat" != "berendsen" ] && [ "$barostat" != "Parrinello-Rahman" ] && [ "$barostat" != "MTTK" ]; then
        echo "Unrecognized barostat: $barostat"
        echo "Supported barostats: berendsen Parrinello-Rahman MTTK"
        exit 1
fi

#RESTRAINT SPRING CONSTANT
if [ "$k_max" -lt "0" ]; then
	echo "Invalid spring constant: $k_max"
	exit 1
fi

#DRUDE SPRING CONSTANT
if [ "$drude_k" -gt "999" ]; then
        echo "Drude spring constant too strong: $drude_k"
        exit 1
elif [ "$drude_k" -lt "1" ]; then
	echo "Drude spring constant too weak: $drude_k"
        exit 1
fi

#LAMBDA POINT
if [ "$Lambda" -lt "0" ] || [ "$Lambda" -gt "100" ]; then
	echo "Invalid Lambda point: $Lambda"
	exit 1
fi

if [ "$MINLAMBDA" -lt "0" ] || [ "$MAXLAMBDA" -gt "100" ] || [ "$MINLAMBDA" -gt "$MAXLAMBDA" ]; then
        echo "Minimum Lambda: $MINLAMBDA"
        echo "Maximum Lambda: $MAXLAMBDA"
        echo "Is not a valid lambda range!"
        exit 1
fi

if [ "$LSPACING" -le "0" ]; then
        echo "Invalid Lambda Spacing: $LSPACING"
        exit 1
fi

if [ "$EXPONENT" -lt "1" ] || [ "$EXPONENT" -gt "4" ]; then
        echo "Invalid Exponent: $EXPONENT"
        exit 1
fi

#GAMMA POINT
if [ "$GSPACING" -le "0" ]; then
        echo "Invalid Gambda Spacing: $GSPACING"
        exit 1
fi

#SIGMAC
if [ "$SigmaC" -le "0" ]; then
        echo "Invalid SigmaC value: $SigmaC"
        exit 1
fi

#SIGMAH
if [ "$SigmaH" -le "0" ]; then
        echo "Invalid SigmaC value: $SigmaH"
        exit 1
fi

#CUTOFF RADIUS
if [ "$CUTOFF" -lt "0" ]; then
	echo "Invalid Cutoff Radius: $CUTOFF"
	exit 1
fi

#POTENTIAL
if [ "$POTENTIAL" != "oplsaa" ] && [ "$POTENTIAL" != "oplsaafakeg" ] && [ "$POTENTIAL" != "oplsaatofakeg" ] && [ "$POTENTIAL" != "oplsaatofakea" ] && [ "$POTENTIAL" != "oplsaafaked" ] && [ "$POTENTIAL" != "oplsaafakea" ] && [ "$POTENTIAL" != "amoeba09" ] && [ "$POTENTIAL" != "amoeba09monop" ] && [ "$POTENTIAL" != "amoeba09mononp" ] && [ "$POTENTIAL" != "amoeba09mononppt" ] && [ "$POTENTIAL" != "amoeba09mononpoop" ] && [ "$POTENTIAL" != "amoeba09multinp" ] && [ "$POTENTIAL" != "amoeba09P2" ]&& [ "$POTENTIAL" != "gromos" ] && [ "$POTENTIAL" != "drude" ]; then
	echo "Invalid Potential: $POTENTIAL"
	echo "Supported Potentials: oplsaa oplsaafakeg oplsaatofakeg oplsaatofakea oplsaafakea oplsaafakegd oplsaafakea amoeba09 amoeba09monop amoeba09mononp amoeba09mononppt amoeba09mononpoop amoeba09multinp amoeba09P2 gromos drude"
	exit 1
fi

#SIMULATION PACKAGE
if [ "$SIMULATION" != "gromacs" ] && [ "$SIMULATION" != "tinker" ]; then
        echo "Invalid Simulation Package: $SIMULATION"
        echo "Supported Simulations: gromacs tinker"
        exit 1
elif [ "$SIMULATION" == "tinker" ]; then
	PRODOUTPUTS="1000"
        PRODTRROUTPUTS="1000"
fi

#ENSEMBLE
if [ "$ENSEMBLE" != "NVE" ] && [ "$ENSEMBLE" != "NVT" ] && [ "$ENSEMBLE" != "NPT" ]; then
	echo "Invalid Thermodynamic Ensemble: $ENSEMBLE"
	echo "Supported Ensembles: NVE, NVT, NPT"
	exit 1	
fi

#=============================================================================================
# FORMAT INPUTS
#=============================================================================================
#Format the temperature name
if [ "$TEMP" -lt "10" ]; then
        export TEMPNAME="00$TEMP"
elif [ "$TEMP" -lt "100" ]; then
        export TEMPNAME="0$TEMP"
else
        export TEMPNAME=$TEMP
fi

#Format the number of molecules
if [ "$MOLECULES" == "$INDEPENDENT" ]; then
	export MOLNAME="$MOLECULES"
else
	export MOLNAME="${MOLECULES}_${INDEPENDENT}ind"
fi

#Format the lambda point name
if [ "$SIMULATION" == "tinker" ]; then
        export LNAME=""
elif [ "$Lambda" -lt "10" ]; then
        export LNAME="_00${Lambda}L"
elif [ "$Lambda" -lt "100" ]; then
        export LNAME="_0${Lambda}L"
else
        export LNAME="_100L"
fi

#Format the gamma point name
if [ "$SIMULATION" == "tinker" ]; then
        export GaNAME=""
elif [ "$GAMMA" -lt "10" ]; then
        export GaNAME="_00${GAMMA}G"
elif [ "$GAMMA" -lt "100" ]; then
        export GaNAME="_0${GAMMA}G"
else
        export GaNAME="_100G"
fi

#Format the DELTA point name
DNAME=$(echo "scale=0;100*${DELTA}" | bc | sed -r 's/^(-?)\./\10./')
DNAME=$(printf "%.0f\n" "$DNAME")
if [ "$SIMULATION" == "tinker" ]; then
        export DNAME=""
elif [ "$DNAME" -lt "10" ]; then
        export DNAME="_00${DNAME}D"
elif [ "$DNAME" -lt "100" ]; then
        export DNAME="_0${DNAME}D"
else
        export DNAME="_100D"
fi

#Format the volume if specified
if [ $VOLUME == "-1" ]; then
	VNAME=""
elif [ "$VOLUME" -lt "10" ]; then
	VNAME=$(echo "$VOLUME*100/1" | bc)
	VNAME="_0${VNAME}V"
elif [ "$VOLUME" -lt "100" ]; then
	VNAME=$(echo "$VOLUME*100/1" | bc)
        VNAME="_${VNAME}V"
else
	VNAME="_${VOLUME}V"
fi

#Format the pressure if specified
if [ $PRESSURE == "-1" ]; then
        PNAME=""
elif [ "$PRESSURE" == "initial" ]; then
	PNAME=""
elif [ "$PRESSURE" -lt "10" ]; then
        PNAME="_00${PRESSURE}P"
elif [ "$PRESSURE" -lt "100" ]; then
        PNAME=$(echo "$PRESSURE*100/1" | bc)
        PNAME="_0${PRESSURE}P"
else
        PNAME="_${PRESSURE}P"
fi

#Format the potential
if [ "$POTENTIAL" == "oplsaa" ]; then
	PotNAME="OPLS";
elif [ "$POTENTIAL" == "oplsaafakeg" ]; then
	PotNAME="FAKEG";
elif [ "$POTENTIAL" == "oplsaatofakeg" ]; then
        PotNAME="OPLSFAKEG";
elif [ "$POTENTIAL" == "oplsaatofakea" ]; then
        PotNAME="OPLSFAKEA";
elif [ "$POTENTIAL" == "oplsaafaked" ]; then
        PotNAME="FAKED";
elif [ "$POTENTIAL" == "oplsaafakea" ]; then
	PotNAME="FAKEA";
elif [ "$POTENTIAL" == "amoeba09" ]; then
	PotNAME="AMO";
elif [ "$POTENTIAL" == "amoeba09P2" ]; then
        PotNAME="AMOP2";
elif [ "$POTENTIAL" == "amoeba09P3" ]; then
        PotNAME="AMOP3";
elif [ "$POTENTIAL" == "amoeba09P4" ]; then
        PotNAME="AMOP4";
elif [ "$POTENTIAL" == "amoeba09P5" ]; then
        PotNAME="AMOP5";
elif [ "$POTENTIAL" == "amoeba09monop" ]; then
        PotNAME="AMOMONOP";
elif [ "$POTENTIAL" == "amoeba09mononp" ]; then
        PotNAME="AMOMONONP";
elif [ "$POTENTIAL" == "amoeba09mononppt" ]; then
        PotNAME="AMOMONONPPT";
elif [ "$POTENTIAL" == "amoeba09mononpoop" ]; then
        PotNAME="AMOMONONPOOP";
elif [ "$POTENTIAL" == "amoeba09multinp" ]; then
        PotNAME="AMOMULTINP";
elif [ "$POTENTIAL" == "gromos" ]; then
	PotNAME="GROM";
elif [ "$POTENTIAL" == "drude" ]; then
	PotNAME="DRUDE"
fi

#Format the charge and Sigma value names
if [ "$POTENTIAL" == "gromos" ] || [ "$POTENTIAL" == "oplsaa" ]; then
    CHARGE="0.1150"
    Chargename=""
    SigmaCname=""
    SigmaHname=""
elif [ "$POTENTIAL" == "drude" ]; then
    CHARGE=""
    Chargename=""
    SigmaCname=""
    SigmaHname=""
elif [ "$POTENTIAL" == "oplsaatofakeg" ] || [ "$POTENTIAL" == "oplsaatofakea" ]; then
    Chargename="_C$(echo $CHARGE | tr -d .)${DNAME}"
    #SigmaCname="_C${SigmaC}"
    #SigmaHname="H${SigmaH}"
    SigmaCname=""
    SigmaHname=""
else
    Chargename="_C$(echo $CHARGE | tr -d .)" 
    #SigmaCname="_C${SigmaC}"
    #SigmaHname="H${SigmaH}"
    SigmaCname=""
    SigmaHname=""
fi

#Format the drude spring constant name
if [ "$SIMULATION" == "tinker" ] || [ "$POTENTIAL" != "drude" ]; then
        export Drudename=""
elif [ "$drude_k" -lt "10" ]; then
        export Drudename="_00${drude_k}D"
elif [ "$drude_k" -lt "100" ]; then
        export Drudename="_0${drude_k}D"
else
        export Drudename="_${drude_k}D"
fi

#Format the simulation
if [ "$SIMULATION" == "gromacs" ]; then
	SimNAME="GRO";
elif [ "$SIMULATION" == "tinker" ]; then
	SimNAME="TIN";
fi


#Format the phase if specified
if [ $PHASE != "DefaultPhase" ]; then
	phase="_${PHASE}"
else
	phase=""
fi

#Format the hinge if specified
if [ $hinge != "DefaultHinge" ]; then
	hinge="_$hinge"
else
	hinge=""
fi

export NAME="benzene"
if [ "$SIMULATION" == "gromacs" ]; then
    export JOBNAME="${NAME}_${SimNAME}_${PotNAME}_${polymorph_num}_${MOLNAME}_${TEMPNAME}K${Chargename}${Drudename}${LNAME}${GaNAME}${PNAME}${VNAME}${hinge}"
else
    export JOBNAME="${NAME}_${SimNAME}_${PotNAME}_${polymorph_num}_${MOLNAME}_${TEMPNAME}K${PNAME}${hinge}"
fi
export JOBPATH="../jobs/${JOBNAME}"
export TEMPLATEPATH="../runfiles"
export GNAME="benzene_pre_EM"
export TNAME="benzene_topology"
export PYTHONSCRIPTPATH="../scripts"

#make the directory if it does not already exist
echo "Making Directory: ${JOBPATH} ..."
mkdir ${JOBPATH}

#OUTPUT FREQUENCY
equil_output_frequency=$(echo "${equil_steps}/${EMOUTPUTS}" | bc)
equil_trr_output_frequency=$(echo "${equil_steps}/${EMTRROUTPUTS}" | bc)
prod_output_frequency=$(echo "${prod_steps}/${PRODOUTPUTS}" | bc)
prod_trr_output_frequency=$(echo "${prod_steps}/${PRODTRROUTPUTS}" | bc)

if [ "$SIMULATION" == "gromacs" ]; then
	#Copy the default equilibration and production mdp file in to the new directory
	echo "Copying .mdp files..."
	if [ ${polymorph_num}  == "gas" ]; then
	    cp ${TEMPLATEPATH}/benzene_minimization_gas.mdp ${JOBPATH}/benzene_minimization.mdp
	    cp ${TEMPLATEPATH}/benzene_equilibration_gas.mdp ${JOBPATH}/benzene_equilibration.mdp
	    cp ${TEMPLATEPATH}/benzene_production_gas.mdp ${JOBPATH}/benzene_production.mdp
	else
	    cp ${TEMPLATEPATH}/benzene_minimization.mdp ${JOBPATH}/benzene_minimization.mdp
	    cp ${TEMPLATEPATH}/benzene_equilibration.mdp ${JOBPATH}/benzene_equilibration.mdp
	    cp ${TEMPLATEPATH}/benzene_production.mdp ${JOBPATH}/benzene_production.mdp
	fi
	echo "Editing .mdp files..."
	#make any necessary adjustments to the mdp file
	#if [ "$integrator" == "sd" ]; then
        #    sed -i 's/comm-mode                = Linear/comm-mode                = None/g' ${JOBPATH}/benzene_equilibration.mdp
        #    sed -i 's/comm-mode                = Linear/comm-mode                = None/g' ${JOBPATH}/benzene_production.mdp
	#fi


	#TEMPERATURE COUPLING
	if [ "$ENSEMBLE" == "NVT" ] || [ "$ENSEMBLE" == "NPT" ]; then
	    sed -i "s/tcoupl                   = v-rescale/tcoupl                   = ${thermostat}/g" ${JOBPATH}/benzene_equilibration.mdp
            sed -i "s/tcoupl                   = v-rescale/tcoupl                   = ${thermostat}/g" ${JOBPATH}/benzene_production.mdp
	    sed -i "s/ref_t.*/ref_t                    = ${TEMP}/g" ${JOBPATH}/benzene_equilibration.mdp
	    sed -i "s/ref_t.*/ref_t                    = ${TEMP}/g" ${JOBPATH}/benzene_production.mdp
	    sed -i "s/gen_temp.*/gen_temp                 = ${TEMP}/g" ${JOBPATH}/benzene_equilibration.mdp
	    sed -i "s/gen_temp.*/gen_temp                 = ${TEMP}/g" ${JOBPATH}/benzene_production.mdp

	fi


	#PRESSURE COUPLING
	if [ "$ENSEMBLE" == "NPT" ]; then
	    sed -i "s/pcoupl                   = no/pcoupl                   = ${barostat}/g" ${JOBPATH}/benzene_equilibration.mdp
	    sed -i "s/pcoupl                   = no/pcoupl                   = ${barostat}/g" ${JOBPATH}/benzene_production.mdp
	    sed -i "s/ref_p.*/ref_p                    = ${PRESSURE} ${PRESSURE} ${PRESSURE} 0.0 0.0 0.0/g" ${JOBPATH}/benzene_equilibration.mdp
	    sed -i "s/ref_p.*/ref_p                    = ${PRESSURE} ${PRESSURE} ${PRESSURE} 0.0 0.0 0.0/g" ${JOBPATH}/benzene_production.mdp
	    #If we are simply interested in getting to the average volume at a new pressure, use a fast time constant
	    if [ "$barostat" == "berendsen" ] && [ "$polymorph_num" != "p3" ]; then
		case $polymorph_num in
		p1 )
		    sed -i "s/tau_p.*/tau_p                    = 1000.0/g" ${JOBPATH}/benzene_equilibration.mdp
                    sed -i "s/tau_p.*/tau_p                    = 1000.0/g" ${JOBPATH}/benzene_production.mdp
		    ;;
		p2 )
		    sed -i "s/tau_p.*/tau_p                    = 1000.0/g" ${JOBPATH}/benzene_equilibration.mdp
                    sed -i "s/tau_p.*/tau_p                    = 1000.0/g" ${JOBPATH}/benzene_production.mdp
		    ;;
		p3 )
		    sed -i "s/tau_p.*/tau_p                    = 1000.0/g" ${JOBPATH}/benzene_equilibration.mdp
                    sed -i "s/tau_p.*/tau_p                    = 1000.0/g" ${JOBPATH}/benzene_production.mdp 
		    ;;
		esac
	    fi
	    #If this is polymorph 3, change the compressibility to allow Beta to change
	    if [ "$polymorph_num" == "p3" ]; then
	        sed -i "s/4.5e-5 4.5e-5 4.5e-5 0 0 0/4.5e-5 4.5e-5 4.5e-5 4.5e-5 4.5e-5 4.5e-5/g" ${JOBPATH}/benzene_equilibration.mdp
	        sed -i "s/4.5e-5 4.5e-5 4.5e-5 0 0 0/4.5e-5 4.5e-5 4.5e-5 4.5e-5 4.5e-5 4.5e-5/g" ${JOBPATH}/benzene_production.mdp
	    fi 
	    #If this is an initial equilibration job, use anisotropic pressure equilibration
	    if [ "$hinge" == "_NPT1" ]; then
		sed -i "s/pcoupltype               = isotropic/;pcoupltype               = isotropic/g" ${JOBPATH}/benzene_equilibration.mdp
		sed -i "s/pcoupltype               = isotropic/;pcoupltype               = isotropic/g" ${JOBPATH}/benzene_production.mdp
		sed -i "s/;pcoupltype               = anisotropic/pcoupltype               = anisotropic/g" ${JOBPATH}/benzene_equilibration.mdp
		sed -i "s/;pcoupltype               = anisotropic/pcoupltype               = anisotropic/g" ${JOBPATH}/benzene_production.mdp
	    fi   
	fi

	#CUTOFF RADIUS
	if [ "$CUTOFF" != "9" ]; then
	    coulombswitch=$(echo "$CUTOFF*0.1 - 0.02" | bc)
	    rcoulomb=$(echo "$CUTOFF*0.1" | bc)
	    vdwswitch=$(echo "$CUTOFF*0.1 - 0.05" | bc)
	    rvdw=$(echo "$CUTOFF*0.1" | bc)
	    sed -i "s/rcoulomb-switch          =.*/rcoulomb-switch          = $coulombswitch/g" ${JOBPATH}/benzene_minimization.mdp
	    sed -i "s/rcoulomb-switch          =.*/rcoulomb-switch          = $coulombswitch/g" ${JOBPATH}/benzene_equilibration.mdp
	    sed -i "s/rcoulomb-switch          =.*/rcoulomb-switch          = $coulombswitch/g" ${JOBPATH}/benzene_production.mdp
	    sed -i "s/rcoulomb                 =.*/rcoulomb                 = $rcoulomb/g" ${JOBPATH}/benzene_minimization.mdp
	    sed -i "s/rcoulomb                 =.*/rcoulomb                 = $rcoulomb/g" ${JOBPATH}/benzene_equilibration.mdp
	    sed -i "s/rcoulomb                 =.*/rcoulomb                 = $rcoulomb/g" ${JOBPATH}/benzene_production.mdp
	    sed -i "s/rvdw-switch              =.*/rvdw-switch              = $vdwswitch/g" ${JOBPATH}/benzene_minimization.mdp
	    sed -i "s/rvdw-switch              =.*/rvdw-switch              = $vdwswitch/g" ${JOBPATH}/benzene_equilibration.mdp
	    sed -i "s/rvdw-switch              =.*/rvdw-switch              = $vdwswitch/g" ${JOBPATH}/benzene_production.mdp
	    sed -i "s/rvdw                     =.*/rvdw                     = $rvdw/g" ${JOBPATH}/benzene_minimization.mdp
	    sed -i "s/rvdw                     =.*/rvdw                     = $rvdw/g" ${JOBPATH}/benzene_equilibration.mdp
	    sed -i "s/rvdw                     =.*/rvdw                     = $rvdw/g" ${JOBPATH}/benzene_production.mdp

	fi

	#EQUILIBRATION/PRODUCTION TIMESTEPS
	sed -i "s/nsteps.*/nsteps                   = ${equil_steps}/g" ${JOBPATH}/benzene_minimization.mdp
	sed -i "s/nsteps.*/nsteps                   = ${equil_steps}/g" ${JOBPATH}/benzene_equilibration.mdp
	sed -i "s/nsteps.*/nsteps                   = ${prod_steps}/g" ${JOBPATH}/benzene_production.mdp

	#OUTPUT FREQUENCY
	sed -i "s/nstlog                   =.*/nstlog                   = ${equil_output_frequency}/g" ${JOBPATH}/benzene_equilibration.mdp
	sed -i "s/nstenergy                =.*/nstenergy                = ${equil_output_frequency}/g" ${JOBPATH}/benzene_equilibration.mdp
	sed -i "s/nstxout               .*/nstxout                  = ${equil_trr_output_frequency}/g" ${JOBPATH}/benzene_equilibration.mdp
	sed -i "s/nstxout-compressed       =.*/nstxout-compressed       = ${equil_trr_output_frequency}/g" ${JOBPATH}/benzene_equilibration.mdp
	sed -i "s/nstlog                   =.*/nstlog                   = ${prod_output_frequency}/g" ${JOBPATH}/benzene_production.mdp
	sed -i "s/nstenergy                =.*/nstenergy                = ${prod_output_frequency}/g" ${JOBPATH}/benzene_production.mdp
	sed -i "s/nstxout               .*/nstxout                  = ${prod_trr_output_frequency}/g" ${JOBPATH}/benzene_production.mdp
	sed -i "s/nstxout-compressed       =.*/nstxout-compressed       = ${prod_trr_output_frequency}/g" ${JOBPATH}/benzene_production.mdp

	#INTEGRATOR
	sed -i "s/integrator.*/integrator               = ${integrator}/g" ${JOBPATH}/benzene_equilibration.mdp
	sed -i "s/integrator.*/integrator               = ${integrator}/g" ${JOBPATH}/benzene_production.mdp

	#FREE ENERGY PARAMETERS
	setup_mdpLambdas -L $Lambda -W $MINLAMBDA -S $MAXLAMBDA -s $LSPACING -A $MAXGAMMA -B $MINGAMMA -G $GAMMA -g $GSPACING -f $EXPONENT -d $JOBPATH

	#Copy over the polymorph gro file
	echo "Copying .gro file..."
	#echo "${TEMPLATEPATH}/benzene_${polymorph_num}_${MOLNAME}_${PRESSURE}bar_${PotNAME}${hinge}.gro ${JOBPATH}/${GNAME}.gro"
	if [ ${polymorph_num}  == "gas" ]; then
		cp ${TEMPLATEPATH}/benzene_p1_72_1bar_gas.gro ${JOBPATH}/${GNAME}.gro
	#If this is an initial equilibration job, use the original polymorph structure
        elif [ "$hinge" == "_NPT1" ]; then
		if [ -f "${TEMPLATEPATH}/benzene_${polymorph_num}_${MOLNAME}_000K_${PotNAME}.gro" ]; then
                        cp ${TEMPLATEPATH}/benzene_${polymorph_num}_${MOLNAME}_000K_${PotNAME}.gro ${JOBPATH}/${GNAME}.gro
                else
                        cp ${TEMPLATEPATH}/benzene_${polymorph_num}_${MOLNAME}.gro ${JOBPATH}/${GNAME}.gro
                fi
	else
		if [ -f "${TEMPLATEPATH}/benzene_${polymorph_num}_${MOLNAME}_${TEMP}K_${PRESSURE}bar_${PotNAME}.gro" ]; then
			cp ${TEMPLATEPATH}/benzene_${polymorph_num}_${MOLNAME}_${TEMP}K_${PRESSURE}bar_${PotNAME}.gro ${JOBPATH}/${GNAME}.gro
		elif [ -f "${TEMPLATEPATH}/benzene_${polymorph_num}_${MOLNAME}_000K_${PotNAME}.gro" ]; then
			cp ${TEMPLATEPATH}/benzene_${polymorph_num}_${MOLNAME}_000K_${PotNAME}.gro ${JOBPATH}/${GNAME}.gro
		else
			cp ${TEMPLATEPATH}/benzene_${polymorph_num}_${MOLNAME}.gro ${JOBPATH}/${GNAME}.gro
		fi
		#scale the box vectors if necessary
		#Determine the current volume of the unit cell 
		if [ "$VOLUME" != "-1" ]; then
			vol=$(echo "$VOLUME*0.01" | bc)
			echo "Resizing to $vol..."
			if [ "$polymorph_num" == "p3" ]; then
				python ${PYTHONSCRIPTPATH}/resize_gro.py -f ${JOBPATH}/${GNAME}.gro -V $vol -M BNZ -n 12 -u 2
			else
				python ${PYTHONSCRIPTPATH}/resize_gro.py -f ${JOBPATH}/${GNAME}.gro -V $vol -M BNZ -n 12 -u 4
			fi
		fi
	fi

	#Copy over the restraint gro file
        echo "Copying restraint file..."
	#echo "${TEMPLATEPATH}/benzene_${polymorph_num}_${MOLNAME}_${PRESSURE}bar_${PotNAME}${hinge}_restraint.gro"
	#exit 1
        if [ ${polymorph_num}  == "gas" ]; then
                cp ${TEMPLATEPATH}/benzene_p1_72_1bar_gas.gro ${JOBPATH}/benzene_restraint.gro
        else
                if [ -f "${TEMPLATEPATH}/benzene_${polymorph_num}_${MOLNAME}_${TEMP}K_${PRESSURE}bar_${PotNAME}_restraint.gro" ]; then
                        cp ${TEMPLATEPATH}/benzene_${polymorph_num}_${MOLNAME}_${TEMP}K_${PRESSURE}bar_${PotNAME}_restraint.gro ${JOBPATH}/benzene_restraint.gro
                else
                        cp ${TEMPLATEPATH}/benzene_${polymorph_num}_${MOLNAME}.gro ${JOBPATH}/benzene_restraint.gro
                fi
        fi
	

	#Copy over the benzene itp file and make the necessary modifications to the bond lengths, charges, and sigma values
	echo "Copying itp file..."
	cp ${TEMPLATEPATH}/benzene_${POTENTIAL}.itp ${JOBPATH}/benzene.itp
	
	#Conduct any interpolations in the itp file
	if [ "$POTENTIAL" != "oplsaatofakeg" ] || [ "$POTENTIAL" != "oplsaatofakea" ]; then
	    python ${SCRIPT_LOC}/interpolate_itp.py -f ${JOBPATH}/benzene.itp -d $DELTA 
	fi

	cp ${TEMPLATEPATH}/parameters.txt ${JOBPATH}/parameters.txt
	snippet=$(echo "$POTENTIAL" | cut -c1-11)
	if [ "$POTENTIAL" == "oplsaa" ]; then
	    sed -i "s/CCCCC/0.140/g" ${JOBPATH}/parameters.txt
	    sed -i "s/HHHHH/0.108/g" ${JOBPATH}/parameters.txt
	elif [ "$POTENTIAL" == "gromos" ]; then
	    sed -i "s/CCCCC/0.139/g" ${JOBPATH}/parameters.txt
            sed -i "s/HHHHH/0.109/g" ${JOBPATH}/parameters.txt
	elif [ "$POTENTIAL" == "drude" ]; then
            sed -i "s/CCCCC/0.1375/g" ${JOBPATH}/parameters.txt
            sed -i "s/HHHHH/0.108/g" ${JOBPATH}/parameters.txt
	    drude_k_strength=$(echo "scale=8;${drude_k}*4184;" | bc | sed -r 's/^(-?)\./\10./')
	    sed -i "s/drude_k/$drude_k_strength/g" ${JOBPATH}/benzene.itp
	elif [ "$snippet" == "oplsaafakeg" ]; then
	    sed -i "s/CCCCC/0.139/g" ${JOBPATH}/parameters.txt
            sed -i "s/HHHHH/0.109/g" ${JOBPATH}/parameters.txt
	elif [ "$snippet" == "oplsaafakegb" ]; then
            sed -i "s/CCCCC/0.139/g" ${JOBPATH}/parameters.txt
            sed -i "s/HHHHH/0.109/g" ${JOBPATH}/parameters.txt
	elif [ "$snippet" == "oplsaafakegd" ]; then
            sed -i "s/CCCCC/0.140/g" ${JOBPATH}/parameters.txt
            sed -i "s/HHHHH/0.108/g" ${JOBPATH}/parameters.txt
	elif [ "$snippet" == "oplsaafakea" ]; then
            sed -i "s/CCCCC/0.1382/g" ${JOBPATH}/parameters.txt
            sed -i "s/HHHHH/0.1079/g" ${JOBPATH}/parameters.txt
	fi
	if [ "$CHARGE" != "" ]; then
	   sed -i "s/-0.115    12.011/-${CHARGE}    12.011/g" ${JOBPATH}/benzene.itp
	   sed -i "s/0.115     1.008/${CHARGE}     1.008/g" ${JOBPATH}/benzene.itp
	fi
	sed -i "s/CCCHARGE/$CHARGE/g" ${JOBPATH}/parameters.txt
	#sed -i "s/opls_145/opls_C${SigmaC}/g" ${JOBPATH}/benzene.itp
        #sed -i "s/opls_146/opls_H${SigmaH}/g" ${JOBPATH}/benzene.itp

	#cp ${TEMPLATEPATH}/benzene.itp ${JOBPATH}/benzene.itp

	#Create the position restraint itp file
	echo "0 0" | gmx genrestr -f ${JOBPATH}/${GNAME}.gro -o ${JOBPATH}/posre.itp -fc $k_max $k_max $k_max| grep "SuppressOutput" 
	#Now lop off all but the first 16 lines
	head -16 ${JOBPATH}/posre.itp > ${JOBPATH}/restr.itp
	#Now exit the position restraint file to indicate a transformation over lambda space (handle all possible spacing cases)

	#Copy over the index file(for the force-averaging code)
	if [ "$MOLECULES" == "$INDEPENDENT" ]; then
        	cp $TEMPLATEPATH/benzene_index.ndx ${JOBPATH}/benzene_index.ndx
		
	else
		cp $TEMPLATEPATH/benzene_${polymorph_num}_${MOLNAME}.ndx ${JOBPATH}/benzene_index.ndx
		sed -i "s/symmetry-averaging       =.*/symmetry-averaging       = yes/g" ${JOBPATH}/benzene_minimization.mdp
		sed -i "s/symmetry-averaging       =.*/symmetry-averaging       = yes/g" ${JOBPATH}/benzene_equilibration.mdp
		sed -i "s/symmetry-averaging       =.*/symmetry-averaging       = yes/g" ${JOBPATH}/benzene_production.mdp
		less "${TEMPLATEPATH}/${INDEPENDENT}ind_symmetry_groups.txt" >> ${JOBPATH}/benzene_minimization.mdp
		less "${TEMPLATEPATH}/${INDEPENDENT}ind_symmetry_groups.txt" >> ${JOBPATH}/benzene_equilibration.mdp
		less "${TEMPLATEPATH}/${INDEPENDENT}ind_symmetry_groups.txt" >> ${JOBPATH}/benzene_production.mdp

	fi



	sed -i "s/$k_max      $k_max      $k_max/0 0 0 $k_max $k_max $k_max/g" ${JOBPATH}/restr.itp
	sed -i "s/$k_max       $k_max       $k_max/0 0 0 $k_max $k_max $k_max/g" ${JOBPATH}/restr.itp
	sed -i "s/$k_max        $k_max        $k_max/0 0 0 $k_max $k_max $k_max/g" ${JOBPATH}/restr.itp
	sed -i "s/$k_max         $k_max         $k_max/0 0 0 $k_max $k_max $k_max/g" ${JOBPATH}/restr.itp
	sed -i "s/$k_max          $k_max          $k_max/0 0 0 $k_max $k_max $k_max/g" ${JOBPATH}/restr.itp

	rm ${JOBPATH}/posre.itp
	mv ${JOBPATH}/restr.itp ${JOBPATH}/posre.itp

	#Copy over the benzene topology file
	echo "Copying topology file..."
	if [ "${polymorph_num}" == "gas" ]; then
		cp ${TEMPLATEPATH}/benzene_gas.top ${JOBPATH}/${TNAME}.top
	else
		cp ${TEMPLATEPATH}/benzene_${MOLECULES}.top ${JOBPATH}/${TNAME}.top
	fi

	#Edit the topology file based on the potential being used
	if [ "$POTENTIAL" == "oplsaafakeg" ]; then
		sed -i 's/oplsaa.ff/oplsaafakeg.ff/g' ${JOBPATH}/${TNAME}.top
	elif [ "$POTENTIAL" == "oplsaatofakeg" ]; then
                sed -i 's/oplsaa.ff/oplsaatofakeg.ff/g' ${JOBPATH}/${TNAME}.top
	elif [ "$POTENTIAL" == "oplsaatofakea" ]; then
		sed -i 's/oplsaa.ff/oplsaatofakea.ff/g' ${JOBPATH}/${TNAME}.top
	elif [ "$POTENTIAL" == "oplsaafaked" ]; then
                sed -i 's/oplsaa.ff/oplsaafaked.ff/g' ${JOBPATH}/${TNAME}.top
	elif [ "$POTENTIAL" == "oplsaafakegd" ]; then
                sed -i 's/oplsaa.ff/oplsaafakegd.ff/g' ${JOBPATH}/${TNAME}.top
	elif [ "$POTENTIAL" == "oplsaafakea" ]; then
                sed -i 's/oplsaa.ff/oplsaafakea.ff/g' ${JOBPATH}/${TNAME}.top
	elif [ "$POTENTIAL" == "gromos" ]; then
		sed -i 's/oplsaa.ff/gromos54a7.ff/g' ${JOBPATH}/${TNAME}.top
	elif [ "$POTENTIAL" == "drude" ]; then
                sed -i 's/oplsaa.ff/drude.ff/g' ${JOBPATH}/${TNAME}.top
		#sed -i "s/benzene $MOLECULES/benzene $(($MOLECULES/2+$MOLECULES))/g" ${JOBPATH}/${TNAME}.top
	fi


	#Copy over local and cluster submission scripts
	echo "Copying local and cluster submission scripts..."
	cp ${TEMPLATEPATH}/submit_local.sh ${JOBPATH}/submit_local.sh
	cp ${TEMPLATEPATH}/submit_localitc.sh ${JOBPATH}/submit_localitc.sh
	cp ${TEMPLATEPATH}/submit_cluster.slurm ${JOBPATH}/submit_cluster.slurm
	sed -i "s/DIRDIRDIRDIR/${JOBNAME}/g" ${JOBPATH}/submit_cluster.slurm
	cp ${TEMPLATEPATH}/submit_cluster_pbs.sh ${JOBPATH}/submit_cluster.sh
	cp ${TEMPLATEPATH}/submit_minim.sh ${JOBPATH}/submit_minim.sh
	cp ${TEMPLATEPATH}/relax_benzene.sh ${JOBPATH}/relax_benzene.sh
	
	#If there is no force-averaging, remove the index file command
	if [ "$MOLECULES" == "$INDEPENDENT" ]; then
	    sed -i "s/-n benzene_index.ndx//g" ${JOBPATH}/submit_local.sh
	    sed -i "s/-n benzene_index.ndx//g" ${JOBPATH}/submit_localitc.sh
	    sed -i "s/-n benzene_index.ndx//g" ${JOBPATH}/submit_cluster.sh
	    sed -i "s/-n benzene_index.ndx//g" ${JOBPATH}/submit_cluster.slurm
	    sed -i "s/-n benzene_index.ndx//g" ${JOBPATH}/relax_benzene.sh
	    sed -i "s/-n benzene_index.ndx//g" ${JOBPATH}/submit_minim.sh
	fi
	
	#If we are not using the drude oscillator potential, remove the drude settings from the mdp file
	if [ "$POTENTIAL" != "drude" ]; then
	    sed -i "/DRUDE-SPECIFIC SETTINGS/,+6d" ${JOBPATH}/benzene_equilibration.mdp
	    sed -i "/DRUDE-SPECIFIC SETTINGS/,+6d" ${JOBPATH}/benzene_production.mdp
	else
	    sed -i "s/gromacs_forceavg2/gromacs_drude/g" ${JOBPATH}/submit_local.sh
            sed -i "s/gromacs_forceavg2/gromacs_drude/g" ${JOBPATH}/submit_localitc.sh
            sed -i "s/gromacs_forceavg2/gromacs_drude/g" ${JOBPATH}/submit_cluster.sh
            sed -i "s/gromacs_forceavg2/gromacs_drude/g" ${JOBPATH}/submit_cluster.slurm
            sed -i "s/gromacs_forceavg2/gromacs_drude/g" ${JOBPATH}/submit_minim.sh
	fi

	#IF WE ARE REWEIGHTING BETWEEN POTENTIALS, SWITCH THE RESTRAINT-LAMBDAS TO DEP-LAMBDAS IN THE MDP FILE	
	if [ "$POTENTIAL" == "oplsaatofakeg" ] || [ "$POTENTIAL" == "oplsaatofakea" ]; then
	    sed -i "s/restraint_lambdas        =/fep-lambdas              =/g" ${JOBPATH}/benzene_equilibration.mdp
            sed -i "s/restraint_lambdas        =/fep-lambdas              =/g" ${JOBPATH}/benzene_production.mdp
	fi
	
	#IF THERE ARE NO VOLUME CHANGES, DONT REWEIGHT, ENERGY MINIMIZE, OR PICK THE AVERAGE CONFIGURATION
	if [ "$ENSEMBLE" == "NVT" ]; then
            sed -i "/RELAX THE BENZENES/,+1d" ${JOBPATH}/submit_localitc.sh
            sed -i "/REWEIGHT THE JOB/,+4d" ${JOBPATH}/submit_localitc.sh
	    sed -i "/RELAX THE BENZENES/,+1d" ${JOBPATH}/submit_cluster.slurm
	    sed -i "/REWEIGHT THE JOB/,+4d" ${JOBPATH}/submit_cluster.slurm
	fi
	
	#SET THE APPROPRIATE POST-SIMULATION REWEIGHTING	
	if [ "$POTENTIAL" == "oplsaa" ]; then
            sed -i "s/reweightjobgromacs -s gromacs -u \"gromos54a7\"/reweightjobgromacs -s gromacs -u \"gromos54a7 oplsaa oplsaafakeg oplsaafakea\"/g" ${JOBPATH}/submit_cluster.slurm
            sed -i "/reweightjobdrude -s gromacs/d" ${JOBPATH}/submit_cluster.slurm
	elif [ "$POTENTIAL" == "oplsaafakea" ] || [ "$POTENTIAL" == "oplsaatofakea" ]; then
	    sed -i "s/reweightjobgromacs -s gromacs -u \"gromos54a7\"/reweightjobgromacs -s gromacs -u \"oplsaafakea\"/g" ${JOBPATH}/submit_cluster.slurm
	    sed -i "/reweightjobdrude -s gromacs/d" ${JOBPATH}/submit_cluster.slurm
	elif [ "$POTENTIAL" == "oplsaafaked" ] || [ "$POTENTIAL" == "drude" ]; then
	    sed -i "s/reweightjobgromacs -s gromacs -u \"gromos54a7\"/reweightjobgromacs -s gromacs -u \"oplsaafaked\"/g" ${JOBPATH}/submit_cluster.slurm
	    sed -i "/convertjobtinker -s gromacs/d" ${JOBPATH}/submit_cluster.slurm
	    if [ "$POTENTIAL" == "drude" ]; then
		sed -i "s/reweightjobdrude -s gromacs/reweightjobdrude -s drude/g" ${JOBPATH}/submit_cluster.slurm
	    fi
	elif [ "$POTENTIAL" == "gromos" ] || [ "$POTENTIAL" == "oplsaafakeg" ]; then
            sed -i "s/reweightjobgromacs -s gromacs -u \"gromos54a7\"/reweightjobgromacs -s gromacs -u \"gromos54a7 oplsaa oplsaafakeg\"/g" ${JOBPATH}/submit_cluster.slurm
	    sed -i "/reweightjobdrude -s gromacs/d" ${JOBPATH}/submit_cluster.slurm
	    sed -i "/convertjobtinker -s gromacs/d" ${JOBPATH}/submit_cluster.slurm
	else
	    sed -i "/convertjobtinker/d" ${JOBPATH}/submit_cluster.slurm
	fi 

	#Set the number of threads
	sed -i "s/-nt 1/-nt ${cores}/g" ${JOBPATH}/submit_local.sh
	sed -i "s/-nt 1/-nt ${cores}/g" ${JOBPATH}/submit_localitc.sh
	sed -i "s/-nt 1/-nt ${cores}/g" ${JOBPATH}/submit_cluster.slurm
	sed -i "s/ntasks=1/ntasks=${cores}/g" ${JOBPATH}/submit_cluster.slurm

elif [ "$SIMULATION" == "tinker" ]; then	

	#Copy over the key and xyz file
	if [ "${polymorph_num}" == "gas" ]; then
		cp ${TEMPLATEPATH}/benzene_gas.key ${JOBPATH}/benzene.key
		cp ${TEMPLATEPATH}/benzene_gas.xyz ${JOBPATH}/benzene.xyz
	else
		if [ -f ${TEMPLATEPATH}/benzene_${polymorph_num}_${MOLECULES}_${PRESSURE}bar.xyz ]; then
			cp ${TEMPLATEPATH}/benzene_${polymorph_num}_${MOLECULES}_${PRESSURE}bar.xyz ${JOBPATH}/benzene.xyz
			cp ${TEMPLATEPATH}/benzene_${polymorph_num}_${MOLECULES}_${PRESSURE}bar.key ${JOBPATH}/benzene.key
		else
			cp ${TEMPLATEPATH}/benzene_${polymorph_num}_${MOLECULES}.xyz ${JOBPATH}/benzene.xyz	
			cp ${TEMPLATEPATH}/benzene_${polymorph_num}_${MOLECULES}.key ${JOBPATH}/benzene.key
		fi
	fi
	
	#Modify the key and file
	if [ "$POTENTIAL" == "oplsaa" ]; then
		sed -i "s/amoeba09.prm/oplsaal.prm/g" ${JOBPATH}/benzene.key
		addatomtypesindividual -p oplsaa -f ${JOBPATH}/benzene.xyz
	elif [ "$POTENTIAL" == "oplsaafake" ]; then
		sed -i "s/amoeba09.prm/oplsaafake.prm/g" ${JOBPATH}/benzene.key
		addatomtypesindividual -p oplsaa -f ${JOBPATH}/benzene.xyz
	elif [ "$POTENTIAL" == "amoeba09" ]; then
		addatomtypesindividual -p amoeba09 -f ${JOBPATH}/benzene.xyz
	elif [ "$POTENTIAL" == "amoeba09P2" ]; then
		sed -i "s/amoeba09.prm/amoeba09P2.prm/g" ${JOBPATH}/benzene.key
                addatomtypesindividual -p amoeba09 -f ${JOBPATH}/benzene.xyz
	elif [ "$POTENTIAL" == "amoeba09P3" ]; then
		sed -i "s/amoeba09.prm/amoeba09P3.prm/g" ${JOBPATH}/benzene.key
                addatomtypesindividual -p amoeba09 -f ${JOBPATH}/benzene.xyz
	elif [ "$POTENTIAL" == "amoeba09P4" ]; then
		sed -i "s/amoeba09.prm/amoeba09P4.prm/g" ${JOBPATH}/benzene.key
                addatomtypesindividual -p amoeba09 -f ${JOBPATH}/benzene.xyz
	elif [ "$POTENTIAL" == "amoeba09P5" ]; then
		sed -i "s/amoeba09.prm/amoeba09P5.prm/g" ${JOBPATH}/benzene.key
                addatomtypesindividual -p amoeba09 -f ${JOBPATH}/benzene.xyz
	elif [ "$POTENTIAL" == "amoeba09monop" ]; then
		sed -i "s/amoeba09.prm/amoeba09monop.prm/g" ${JOBPATH}/benzene.key
                addatomtypesindividual -p amoeba09 -f ${JOBPATH}/benzene.xyz
	elif [ "$POTENTIAL" == "amoeba09mononp" ]; then
		sed -i "s/amoeba09.prm/amoeba09mononp.prm/g" ${JOBPATH}/benzene.key
                addatomtypesindividual -p amoeba09 -f ${JOBPATH}/benzene.xyz
	elif [ "$POTENTIAL" == "amoeba09mononppt" ]; then
                sed -i "s/amoeba09.prm/amoeba09mononppt.prm/g" ${JOBPATH}/benzene.key
                addatomtypesindividual -p amoeba09 -f ${JOBPATH}/benzene.xyz
	elif [ "$POTENTIAL" == "amoeba09mononpoop" ]; then
                sed -i "s/amoeba09.prm/amoeba09mononpoop.prm/g" ${JOBPATH}/benzene.key
                addatomtypesindividual -p amoeba09 -f ${JOBPATH}/benzene.xyz
	elif [ "$POTENTIAL" == "amoeba09multinp" ]; then
		sed -i "s/amoeba09.prm/amoeba09multinp.prm/g" ${JOBPATH}/benzene.key
                addatomtypesindividual -p amoeba09 -f ${JOBPATH}/benzene.xyz
	fi
	
	#X=$(sed -n '4p' benzene.xyz | awk '{print $2}')
	#sed -i "s/XXXX/$X/g" ${JOBPATH}/benzene.key
	#Y=$(sed -n '4p' benzene.xyz | awk '{print $3}')
	#sed -i "s/YYYY/$Y/g" ${JOBPATH}/benzene.key
	#Z=$(sed -n '4p' benzene.xyz | awk '{print $4}')
	#sed -i "s/ZZZZ/$Z/g" ${JOBPATH}/benzene.key
	#alpha=$(sed -n '4p' benzene.xyz | awk '{print $5}')
	#sed -i "s/AAAA/$alpha/g" ${JOBPATH}/benzene.key
	#beta=$(sed -n '4p' benzene.xyz | awk '{print $6}')
	#sed -i "s/BBBB/$beta/g" ${JOBPATH}/benzene.key
	#gamma=$(sed -n '4p' benzene.xyz | awk '{print $7}')
	#sed -i "s/GGGG/$gamma/g" ${JOBPATH}/benzene.key
	

	#Copy over the job specs file
	cp ${TEMPLATEPATH}/job_specs.txt ${JOBPATH}/job_specs.txt
	sed -i "s/SSSS/$prod_steps/g" ${JOBPATH}/job_specs.txt
	sed -i "s/dtdt/0.5/g" ${JOBPATH}/job_specs.txt
	output_frac=$(echo "scale=8;x=1/${prod_output_frequency}; if(x<1) print 0; x" | bc)
	output_dt=$(echo "scale=4;x=${prod_output_frequency}*0.5*0.001; if(x<1) print 0; x" | bc)
	sed -i "s/XXXX/${output_dt}/g" ${JOBPATH}/job_specs.txt
	sed -i "s/TTTT/$TEMP/g" ${JOBPATH}/job_specs.txt
	if [ $ENSEMBLE == "NPT" ]; then
	    sed -i "s/EEEE/4   /g" ${JOBPATH}/job_specs.txt
	    sed -i "s/(NVT)/(NPT)/g" ${JOBPATH}/job_specs.txt
	    sed -i "s/PPPP/$PRESSURE/g" ${JOBPATH}/job_specs.txt
	else
	    sed -i "s/EEEE/2   /g" ${JOBPATH}/job_specs.txt
            sed -i "s/PPPP//g" ${JOBPATH}/job_specs.txt
	fi



	#Copy over local and cluster submission scripts
	echo "Copying local and cluster submission scripts..."
        cp ${TEMPLATEPATH}/submit_localitc_tinker.sh ${JOBPATH}/submit_localitc.sh
        cp ${TEMPLATEPATH}/submit_cluster_tinker.slurm ${JOBPATH}/submit_cluster.slurm

	#Modify the local and cluster submission scripts
	sed -i "s/SSSS/$prod_steps/g" ${JOBPATH}/submit_cluster.slurm
	sed -i "s/SSSS/$prod_steps/g" ${JOBPATH}/submit_localitc.sh
        sed -i "s/dtdt/0.5/g" ${JOBPATH}/submit_cluster.slurm
	sed -i "s/dtdt/0.5/g" ${JOBPATH}/submit_localitc.sh
        output_dt=$(echo "scale=4;x=${prod_output_frequency}*0.5*0.001; if(x<1) print 0; x" | bc)
        sed -i "s/XXXX/${output_dt}/g" ${JOBPATH}/submit_cluster.slurm
	sed -i "s/XXXX/${output_dt}/g" ${JOBPATH}/submit_localitc.sh
        sed -i "s/TTTT/$TEMP/g" ${JOBPATH}/submit_cluster.slurm
	sed -i "s/TTTT/$TEMP/g" ${JOBPATH}/submit_localitc.sh
	if [ $ENSEMBLE == "NPT" ]; then
	    sed -i "s/EEEE/4   /g" ${JOBPATH}/submit_cluster.slurm
            sed -i "s/EEEE/4   /g" ${JOBPATH}/submit_localitc.sh
	    sed -i "s/PPPP/$PRESSURE/g" ${JOBPATH}/submit_cluster.slurm
            sed -i "s/PPPP/$PRESSURE/g" ${JOBPATH}/submit_localitc.sh
	else
	    sed -i "s/EEEE/2   /g" ${JOBPATH}/submit_cluster.slurm
            sed -i "s/EEEE/2   /g" ${JOBPATH}/submit_localitc.sh
            sed -i "s/PPPP//g" ${JOBPATH}/submit_cluster.slurm
            sed -i "s/PPPP//g" ${JOBPATH}/submit_localitc.sh
	fi

	#Set the number of threads
        sed -i "s/-nt 1/-nt ${cores}/g" ${JOBPATH}/submit_localitc.sh
        sed -i "s/-nt 1/-nt ${cores}/g" ${JOBPATH}/submit_cluster.slurm
        sed -i "s/ntasks=1/ntasks=${cores}/g" ${JOBPATH}/submit_cluster.slurm


fi

echo "Create the job status file"
echo "UNSUBMITTED" > ${JOBPATH}/jobstatus.txt

echo "Creating .initial directory"
mkdir ${JOBPATH}/.initial
for file in $(ls ${JOBPATH}); do
    cp ${JOBPATH}/$file ${JOBPATH}/.initial/$file
done

echo "Done!"

